server {
    listen 8080;
    server_tokens off; # Hide nginx version
    server_name localhost;
    root /usr/share/nginx/html/codes;
    index index.html;

    location /media/ {
        alias /usr/share/nginx/html/media/;
        autoindex on;
        autoindex_format json;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }

    # add_header ... always; means that the header will be added to all responses, including error responses

    # browser must respect the declared file type, 
    # eg: if the server says it's a text/plain, browser will not guess that it is HTML or JavaScript
    add_header X-Content-Type-Options "nosniff" always;
    
    # browser will not send the Referer header to any site, including the same site
    add_header Referrer-Policy "no-referrer" always; 
    
    # prevent clickjacking attacks by disallowing the site to be embedded in frames
    add_header X-Frame-Options "DENY" always; 
    
    # empty parentheses mean "nobody may use this browser feature"
    add_header Permissions-Policy "camera=(), microphone=(), geolocation=()" always;
}